# Generated by Django 4.1 on 2022-08-19 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product', models.CharField(max_length=30, unique=True)),
                ('Description', models.CharField(max_length=280)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Project_Especification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diameter', models.CharField(max_length=10, unique=True)),
                ('Length', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Project Especification',
                'verbose_name_plural': 'Projects Especifications',
            },
        ),
        migrations.CreateModel(
            name='ProviderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimaryEmail', models.EmailField(max_length=254)),
                ('SecondaryEmail', models.EmailField(max_length=254)),
                ('PrimaryPhone', models.CharField(max_length=16)),
                ('SecondaryPhone', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'Provider Group',
                'verbose_name_plural': 'Providers Groups',
            },
        ),
        migrations.CreateModel(
            name='ProviderGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group', models.CharField(max_length=30)),
                ('Country', models.CharField(max_length=40)),
                ('Abbreviation', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Provider Group',
                'verbose_name_plural': 'Providers Groups',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(choices=[('ADM', 'Admin'), ('DEV', 'Developer'), ('CMM', 'Comum')], default='CLR', max_length=3)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255, unique=True)),
                ('CNPJ', models.CharField(max_length=20)),
                ('Initials', models.CharField(max_length=15)),
                ('Contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.providercontact')),
                ('Group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.providergroup')),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
            },
        ),
        migrations.CreateModel(
            name='Project_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemDate', models.DateField(blank=True, null=True)),
                ('ProductionDate', models.DateField(blank=True, null=True)),
                ('BatchTracking', models.CharField(blank=True, max_length=60)),
                ('quantity', models.IntegerField(blank=True, default=None, null=True)),
                ('especification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.project_especification')),
            ],
            options={
                'verbose_name': 'Project Data',
                'verbose_name_plural': 'Projects Data',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(max_length=30, unique=True)),
                ('Data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.project_data')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.product')),
                ('Provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.provider')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=30)),
                ('LastName', models.CharField(max_length=30)),
                ('EDV', models.CharField(max_length=10, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('Username', models.CharField(blank=True, max_length=10)),
                ('Role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SafeLaunch.role')),
            ],
            options={
                'verbose_name': 'Collaborator',
                'verbose_name_plural': 'Collaborators',
            },
        ),
    ]
